-- THE DESCENT — Phase 3.3 Supabase Content Engine Migration
-- Run once in Supabase SQL Editor AFTER the existing Phase 2 schema.
-- Uses the browser publishable/anon key with RLS. NEVER expose service_role.
create extension if not exists pgcrypto;
create or replace function public.is_gm() returns boolean language sql stable security definer set search_path=public as $$
 select exists(select 1 from public.profiles p where p.id=auth.uid() and lower(coalesce(p.role,''))='gm');
$$;
create table if not exists public.content_packs (id uuid primary key default gen_random_uuid(),name text not null,description text,source_authority text not null default 'THE_DESCENT',tags text[] not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_items (id text primary key,name text not null,category text not null default 'misc',gear_slot text,tier text,floor_min integer,data jsonb not null default '{}'::jsonb,source_authority text not null default 'THE_DESCENT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_npcs (id text primary key,name text not null,npc_type text,floor_min integer,data jsonb not null default '{}'::jsonb,source_authority text not null default 'THE_DESCENT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_adversaries (id text primary key,name text not null,classification text,floor_min integer,data jsonb not null default '{}'::jsonb,source_authority text not null default 'THE_DESCENT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_encounters (id text primary key,name text not null,floor_min integer,data jsonb not null default '{}'::jsonb,source_authority text not null default 'THE_DESCENT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_quests (id text primary key,name text not null,scope text not null default 'Individual',data jsonb not null default '{}'::jsonb,source_authority text not null default 'THE_DESCENT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_achievements (id text primary key,name text not null,reward_tier text,data jsonb not null default '{}'::jsonb,source_authority text not null default 'THE_DESCENT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.content_loot_boxes (id text primary key,name text not null,tier text not null default 'bronze',box_type text,data jsonb not null default '{}'::jsonb,source_authority text not null default 'THE_DESCENT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.system_events (id text primary key,name text not null,event_type text not null,recipient_id text,priority text not null default 'normal',presentation text not null default 'popup',status text not null default 'delivered',related_object_type text,related_object_id text,data jsonb not null default '{}'::jsonb,source_authority text not null default 'THE_DESCENT',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.active_encounters (id text primary key,definition_id text,name text not null,status text not null default 'active',round integer not null default 1,phase text not null default 'mobs',floor integer not null default 1,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
do $$ declare t text; begin foreach t in array array['content_packs','content_items','content_npcs','content_adversaries','content_encounters','content_quests','content_achievements','content_loot_boxes','system_events','active_encounters'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
do $$ declare t text; begin foreach t in array array['content_packs','content_items','content_npcs','content_adversaries','content_encounters','content_quests','content_achievements','content_loot_boxes'] loop
 execute format('drop policy if exists %I on public.%I','content_read_'+t,t);execute format('create policy %I on public.%I for select to authenticated using (true)','content_read_'+t,t);
 execute format('drop policy if exists %I on public.%I','content_gm_write_'+t,t);execute format('create policy %I on public.%I for all to authenticated using (public.is_gm()) with check (public.is_gm())','content_gm_write_'+t,t);end loop;end $$;
drop policy if exists system_events_gm_all on public.system_events;create policy system_events_gm_all on public.system_events for all to authenticated using (public.is_gm()) with check (public.is_gm());
drop policy if exists system_events_recipient_read on public.system_events;create policy system_events_recipient_read on public.system_events for select to authenticated using (recipient_id is null or recipient_id=auth.uid()::text or public.is_gm());
drop policy if exists active_encounters_read on public.active_encounters;create policy active_encounters_read on public.active_encounters for select to authenticated using (true);
drop policy if exists active_encounters_gm_write on public.active_encounters;create policy active_encounters_gm_write on public.active_encounters for all to authenticated using (public.is_gm()) with check (public.is_gm());
do $$ begin begin alter publication supabase_realtime add table public.system_events; exception when duplicate_object then null; end;begin alter publication supabase_realtime add table public.active_encounters; exception when duplicate_object then null; end;end $$;
create index if not exists idx_content_items_category on public.content_items(category);create index if not exists idx_content_adversaries_class on public.content_adversaries(classification);create index if not exists idx_system_events_recipient on public.system_events(recipient_id,created_at desc);create index if not exists idx_active_encounters_status on public.active_encounters(status,created_at desc);
